version: '3.1'

services:
    mongo:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        volumes:
            - hw4_mongo_volume:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        ports:
            - "27017:27017"

    express:
        build: ./backend/
        env_file:
            - './backend/.env'
        environment:
            - PORT=8080
        ports:
            - "8080:8080"
        depends_on:
            - mongo

    react:
        build: ./frontend/
        volumes:
            - './frontend/:/app'
            - '/app/node_modules'
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
        command: yarn start
        depends_on:
            - express

volumes:
    hw4_mongo_volume:
